CREATE TABLE product (
  id serial primary key,
  name varchar(500)
);

INSERT INTO product(id, name) VALUES (696815, 'Tênis adidas Essence 10 - Masculino AMARELO/AZUL TAMANHO 33');
INSERT INTO product(id, name) VALUES (640355, 'Tênis Puma Archive Lite Lo Ruged Core – Unissex PRETO TAMANHO 37');
INSERT INTO product(id, name) VALUES (772462, 'INTRODUCAO A ECONOMIA  20ª EDICAO');
INSERT INTO product(id, name) VALUES (708312, 'Encordoamento para Violao GENW Canario NYLON Medio Giannini');
INSERT INTO product(id, name) VALUES (691050, 'Camiseta adidas Response 3 Stripes 2009 Feminina VERDE CLARO/CINZA TAMANHO EX');
INSERT INTO product(id, name) VALUES (705977, 'Kit Suporte Articulado para TV Curved - Inclinável - 32" a 65" +  Suporte de Parede para DVD');
INSERT INTO product(id, name) VALUES (829295, 'Protetor de Borda de Stand Up Railsaver Prata');
INSERT INTO product(id, name) VALUES (492229, 'Guarda-Roupa 3 Portas Multimóveis Tutti-Frutti');
INSERT INTO product(id, name) VALUES (817723, 'Dobradiça de Chapa para Portão 4"');
INSERT INTO product(id, name) VALUES (630312, 'Tênis adidas Cleaser Cf I - Infantil BRANCO/AZUL ESC TAMANHO 23');
INSERT INTO product(id, name) VALUES (806087, 'Bolsa Térmica Take Away M com 4 Potes Plus NC159 - Notecare - PRETA');
INSERT INTO product(id, name) VALUES (642916, 'Chinelo adidas Star 3G - Masculino AZUL/BRANCO TAMANHO 42');
INSERT INTO product(id, name) VALUES (722991, 'Tênis Puma Faas 800 - Feminino CINZA CLA/AZUL TAMANHO 36');
INSERT INTO product(id, name) VALUES (722309, 'Tênis Puma Benny Canvas MARROM/MARROM CLA TAMANHO 35');
INSERT INTO product(id, name) VALUES (392925, 'Toalha de Mesa Redonda Roxa Colorline');
INSERT INTO product(id, name) VALUES (760446, 'Rack Modena TB253 Branco Brilho- DallaCosta');
INSERT INTO product(id, name) VALUES (525690, 'Biquíni Calcinha Elaine Tanga Lycra Roxo G');
INSERT INTO product(id, name) VALUES (735701, 'Eletrosserra 2200 Watts - 220 Volts - Nes2200 -Nagano');
INSERT INTO product(id, name) VALUES (636932, 'Tênis Mizuno Wave Lightning RX 3 – Feminino ROXO/BRANCO TAMANHO 39');
INSERT INTO product(id, name) VALUES (464135, 'Cartucho Epson C63 | C65 | C83 | C85 | TO46120 Preto Original 15ml');
INSERT INTO product(id, name) VALUES (709243, 'TV  LG 28LB700B LED IPS 28" HDMI e Conversor Digital');
INSERT INTO product(id, name) VALUES (657841, 'Jaqueta adidas Firebird 1 - Feminina ROSA/BRANCO TAMANHO EX');
INSERT INTO product(id, name) VALUES (442481, 'FLUOR - G');
INSERT INTO product(id, name) VALUES (801653, 'Game Lego Batman 3 (Versão em Português) - PS4');
INSERT INTO product(id, name) VALUES (832622, 'Termômetro Digital Com Ponta Flexível G-Tech Sapo');
INSERT INTO product(id, name) VALUES (630422, 'Tênis adidas Originals adi Ease Surf – Masculino MARROM CLARO TAMANHO 33');
INSERT INTO product(id, name) VALUES (818862, 'Porca Calota Inox 5/16"unc ');
INSERT INTO product(id, name) VALUES (766029, 'Linha Anchor Raiom 8m - [ 50374 ]');
INSERT INTO product(id, name) VALUES (810121, 'Bain de Terre Purité Healthy Shampoo Color Protect - Shampoo 400ml');
INSERT INTO product(id, name) VALUES (665606, 'Tênis adidas Vanquish 5 Lea - Feminino BRANCO/ROXO TAMANHO 34');
INSERT INTO product(id, name) VALUES (782652, 'Um Doce Redondo com Tampa Articulado com 300 Unidades Starpack');
INSERT INTO product(id, name) VALUES (710451, 'T-Shirt Clássica VR São Paulo-M');
INSERT INTO product(id, name) VALUES (523765, 'Da Internet Ao Grid - A Globalizacao Do Processame');
INSERT INTO product(id, name) VALUES (495261, 'Cabo Vivitar de Sincronismo e Carga Para IPad, IPhone e IPod V10188C-IPD');
INSERT INTO product(id, name) VALUES (624984, 'Capa + Película Asha 501 Silicone TPU Premium - Husky - Transparente');
INSERT INTO product(id, name) VALUES (683713, 'Chuteira de Campo adidas Ace 15.3 FG PRETO/VERDE CLA TAMANHO 39');
INSERT INTO product(id, name) VALUES (535424, 'Guitarra Pacífica 012 Vermelho - Yamaha');
INSERT INTO product(id, name) VALUES (810782, 'Condicionador Acquaflora Equilíbrio Oleosidade Normais ou Mistos 300ml');
INSERT INTO product(id, name) VALUES (753099, 'Globo Real Base Arco Médio Fullway - 17x14 cm');
INSERT INTO product(id, name) VALUES (820498, 'Jogo de Alicates JR861 - Com 5 Peças');
INSERT INTO product(id, name) VALUES (420332, 'MODELO CONTEMPORANEO DA GESTAO A BRASILEIRA');
INSERT INTO product(id, name) VALUES (810836, 'Condicionador Leave-in Tigi Catwalk Curlesque Leave-in Conditioner 215ml');
INSERT INTO product(id, name) VALUES (802524, 'Papel de Parede Adesivo Autocolante Pedras Tipo Canjiquinha 0125');
INSERT INTO product(id, name) VALUES (641160, 'Cama Adicional Amarela');
INSERT INTO product(id, name) VALUES (631125, 'Chuteira Society adidas Nitrocharge 3.0 TF  PRETO/LARANJA CLA TAMANHO 36');
INSERT INTO product(id, name) VALUES (494160, 'Vaso Auto irrigável GRANDE 21,5 cm X 18 cm - Com escolha de cor');
INSERT INTO product(id, name) VALUES (549302, 'Camiseta  adidas Regista - Masculina PRETO TAMANHO P');
INSERT INTO product(id, name) VALUES (590374, 'Tênis Puma Maeko S - Infantil  PRETO/CINZA ESC TAMANHO 24');
INSERT INTO product(id, name) VALUES (713845, 'Camiseta adidas F50 SS13 - Masculina Azul Esc/Amarelo TAMANHO P');
INSERT INTO product(id, name) VALUES (528553, 'Seguranca Publica');
INSERT INTO product(id, name) VALUES (546350, 'Bermuda adidas 3s Ess - Masculina PRETO/BRANCO TAMANHO G');
INSERT INTO product(id, name) VALUES (526838, 'CRIADO-MUDO SEM FUNDO AMARELO NOVO - PHORMAN');
INSERT INTO product(id, name) VALUES (633831, 'Tênis Mizuno Wave Enigma 3 - Feminino ROSA/PRATA TAMANHO 43');
INSERT INTO product(id, name) VALUES (777272, 'CUECA SLIP ALGODÃO COM ABERTURA PRETA GG');
INSERT INTO product(id, name) VALUES (511023, 'Cadeira Asa - Falkk Design');
INSERT INTO product(id, name) VALUES (474381, 'Cooktop a Gás 4 Bocas Glass Brasil 4GG 55 Tramontina 94703501');
INSERT INTO product(id, name) VALUES (385750, 'MISTERIO E A HISTORIA, O - ENSAIOS DE TEOLOGIA...');
INSERT INTO product(id, name) VALUES (612401, 'Tênis Mizuno Wave Enigma 4 – Feminino VERDE/ROSA TAMANHO 42');
INSERT INTO product(id, name) VALUES (728187, 'Tênis Asics Gel Nimbus 13 - Feminino PRETO/VERDE TAMANHO 35');
INSERT INTO product(id, name) VALUES (395902, 'Painel Frontal Prelude 1992 a 1995');
INSERT INTO product(id, name) VALUES (724236, 'Tênis Under Armour Micro G Assert V – Masculino PRETO/VERDE TAMANHO 45');
INSERT INTO product(id, name) VALUES (427094, 'Strider Bike Classic - Azul');
INSERT INTO product(id, name) VALUES (616911, 'Tênis Asics Gel Lyte 33 - Masculino CINZA ESC/VERMELHO TAMANHO 46');
INSERT INTO product(id, name) VALUES (596920, 'Tênis adidas Mega Torsion Rsp II - Masculino BRANCO/AZUL TAMANHO 43');
INSERT INTO product(id, name) VALUES (524672, 'Genese Da Ideia De Tempo E Outros Escritos, A');
INSERT INTO product(id, name) VALUES (407112, 'BOTA DE MALHA FEMININA VIENA Azul Marinho 36_37 RICSEN 6975');
INSERT INTO product(id, name) VALUES (516132, 'Tratados De Terra E Gente Do Brasil');
INSERT INTO product(id, name) VALUES (736880, 'Forno Elétrico 48 Litros com Função Timer Philco - 110v');
INSERT INTO product(id, name) VALUES (462955, 'CINZA-UN');
INSERT INTO product(id, name) VALUES (527544, 'Milindapanha Ou As Perguntas Do Rei Menandro');
INSERT INTO product(id, name) VALUES (638837, 'Camiseta Regata adidas Clima Training – Masculina  CINZA ESCURO TAMANHO EX');
INSERT INTO product(id, name) VALUES (484112, 'Conjunto Talheres Dobraveis Trekker com Estojo');
INSERT INTO product(id, name) VALUES (584721, 'Tênis adidas Feather Elite 2 – Masculino AZUL CLA/AZUL ESC TAMANHO 43');
INSERT INTO product(id, name) VALUES (659075, 'Camisa adidas Milan III s/nº  2012 - Masculina PRETO/VERMELHO TAMANHO EX');
INSERT INTO product(id, name) VALUES (442045, 'Cueca Boxer Microfibra Zeus Ryjor Listras Preto GG');
INSERT INTO product(id, name) VALUES (757448, 'Linha para Costura 120 Círculo 1371m - [ 185 ]');
INSERT INTO product(id, name) VALUES (475514, 'Kit 4 Pneus Marshal MU11 (215/40R17 87W)');
INSERT INTO product(id, name) VALUES (569053, 'História do The Cure. A: Nunca É o Bastante');
INSERT INTO product(id, name) VALUES (828202, 'BRANCO/LARANJA - 56');
INSERT INTO product(id, name) VALUES (741857, 'MALA GRANDE PRETA - TRAVEL MAX');
INSERT INTO product(id, name) VALUES (685405, 'Camiseta Regata Puma Racerback Tank Top - Feminina PRETO TAMANHO M');
INSERT INTO product(id, name) VALUES (401303, 'Almofada 40x40 Onça na Floresta');
INSERT INTO product(id, name) VALUES (529437, 'CORAL-00EG');
INSERT INTO product(id, name) VALUES (677812, 'Chuteira Society Under Armour Speed Force TR PRETO/BRANCO TAMANHO 45');
INSERT INTO product(id, name) VALUES (713169, 'Caneleira Puma Universal - Adulto Amarelo/Preto TAMANHO P');
INSERT INTO product(id, name) VALUES (696692, 'Chuteira Society Mizuno Wave Ignitus 3 TF AMARELO/AZUL TAMANHO 51');
INSERT INTO product(id, name) VALUES (481795, 'Moranguinho - Estojo Duplo Furry Friends - Xeryus');
INSERT INTO product(id, name) VALUES (390404, 'Jogo de Brocas Vonder 25 Peças 1 - 13mm - Vonder');
INSERT INTO product(id, name) VALUES (457195, 'Rio Ing Cpi (Imp-Eua) Ps3');
INSERT INTO product(id, name) VALUES (521648, 'Show De Sabores - Dicas E Receitas Faceis E Pratic');
INSERT INTO product(id, name) VALUES (801128, 'Blusa Zip Thermo Fleece Feminina VTB002 - Curtlo - VERMELHA - M');
INSERT INTO product(id, name) VALUES (667326, 'Tênis Puma Whirlwind V - Infantil AZUL ESC/VERMELHO TAMANHO 26');
INSERT INTO product(id, name) VALUES (415405, 'Comoda Mega Carvalho Gloss com Preto - Mirarack');
INSERT INTO product(id, name) VALUES (732795, 'Jogo de Banheiro Formato Chinelo 03 Peças - Pink');
INSERT INTO product(id, name) VALUES (468654, 'Mesa Multiuso Dobrável Tecno Mobili ME4117');
INSERT INTO product(id, name) VALUES (578600, 'Bermuda adidas Clima 365 - Masculina - 778004 AZUL ESCURO TAMANHO G');
INSERT INTO product(id, name) VALUES (487986, 'Alimentador Munchkin');
INSERT INTO product(id, name) VALUES (632189, 'Tênis adidas Naloa III - Feminino BRANCO/PRETO TAMANHO 38');
INSERT INTO product(id, name) VALUES (764999, 'Fio Cisne Little Sweet 100g - [ 0100 ]');
INSERT INTO product(id, name) VALUES (384276, 'Essência da Mente, A: Usando Seu Poder Interior Para Mudar');
